version: '3'

services:
#  api:
#    container_name: api
#    image: bunnyfood-api
#    depends_on:
#      - db
#    environment:
#      - DB_HOST=db
#    ports:
#      - '8000:8000'
#    networks:
#      - bunnyfood
#    restart: unless-stopped

  db:
    container_name: db
    image: postgres:13.7-alpine
    environment:
      POSTGRES_DB: bunnyfood_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      bunnyfood:
        ipv4_address: 172.18.0.10
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
      - ./data/servers.json:/pgadmin4/servers.json
    ports:
      - "8080:80"
    networks:
      - bunnyfood
    restart: unless-stopped

networks:
  bunnyfood:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24