"""removed media_url limit

Revision ID: 161a79fc7c68
Revises: 77e77da77570
Create Date: 2022-08-28 16:50:18.460481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161a79fc7c68'
down_revision = '77e77da77570'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
