"""add post score

Revision ID: 1b5f29f22501
Revises: c0593994b920
Create Date: 2022-08-25 10:24:59.032469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5f29f22501'
down_revision = 'c0593994b920'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'score')
    # ### end Alembic commands ###
