"""add location last_scored

Revision ID: 1befb51b998d
Revises: da2ebb0af228
Create Date: 2022-08-28 10:44:23.897827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1befb51b998d'
down_revision = 'da2ebb0af228'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('last_scored', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'last_scored')
    # ### end Alembic commands ###
