"""removed location name unique constraint

Revision ID: 238bb2a0525e
Revises: 6ce8d444b850
Create Date: 2022-09-01 10:49:06.490011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238bb2a0525e'
down_revision = '6ce8d444b850'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('locations_name_key', 'locations', type_='unique')
    op.create_unique_constraint(None, 'locations', ['maps_place_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='unique')
    op.create_unique_constraint('locations_name_key', 'locations', ['name'])
    # ### end Alembic commands ###
