"""location name unique

Revision ID: 35b1188f1609
Revises: d41675f500b4
Create Date: 2022-08-20 14:17:55.276427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b1188f1609'
down_revision = 'd41675f500b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'locations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='unique')
    # ### end Alembic commands ###
