"""add location address and maps_place_id

Revision ID: 6ce8d444b850
Revises: a557f1403100
Create Date: 2022-09-01 10:43:05.074767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce8d444b850'
down_revision = 'a557f1403100'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('maps_place_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'maps_place_id')
    op.drop_column('locations', 'address')
    # ### end Alembic commands ###
