"""add gramhir profiles table

Revision ID: 77e77da77570
Revises: 1befb51b998d
Create Date: 2022-08-28 16:21:13.691618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e77da77570'
down_revision = '1befb51b998d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gramhirprofiles',
    sa.Column('gramhir_id', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('gramhir_id', 'username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gramhirprofiles')
    # ### end Alembic commands ###
