"""add post columns

Revision ID: 8e6107172466
Revises: 35b1188f1609
Create Date: 2022-08-22 15:51:39.928096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6107172466'
down_revision = '35b1188f1609'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('shortcode', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('media_url', sa.String(length=512), nullable=True))
    op.add_column('posts', sa.Column('media_s3_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'posts', ['shortcode'])
    op.create_unique_constraint(None, 'posts', ['media_s3_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'media_s3_key')
    op.drop_column('posts', 'media_url')
    op.drop_column('posts', 'caption')
    op.drop_column('posts', 'shortcode')
    # ### end Alembic commands ###
