"""add post media_type

Revision ID: c0593994b920
Revises: 8e6107172466
Create Date: 2022-08-22 15:54:01.637152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0593994b920'
down_revision = '8e6107172466'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'media_type')
    # ### end Alembic commands ###
