"""add socialprofile last_scraped

Revision ID: da2ebb0af228
Revises: 1b5f29f22501
Create Date: 2022-08-28 10:43:32.096040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2ebb0af228'
down_revision = '1b5f29f22501'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socialprofiles', sa.Column('last_scraped', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('socialprofiles', 'last_scraped')
    # ### end Alembic commands ###
