openapi: 3.0.0
info:
  title: BunnyFood API
  version: 0.1.0
  
paths:
  /locations/{locationId}:
    get:
      summary: Returns a Location by ID
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Location in JSON format
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        '404':
          description: Location not found
                
  /locations:
    get:
      summary: Returns all Location
      responses:
        '200':
          description: JSON array of Location
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Location'
                  
  /profiles/{profileId}:
    get:
      summary: Returns a SocialProfile by ID
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: SocialProfile in JSON format
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SocialProfile'
        '404':
          description: SocialProfile not found
                
  /profiles:
    get:
      summary: Returns all followed SocialProfile
      responses:
        '200':
          description: JSON array of SocialProfile
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/SocialProfile'
    post:
      summary: Add a new SocialProfile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: ic3peak
      responses:
        '200':
          description: SocialProfile successfully added
        '404':
          description: SocialProfile with specified username not existing
                  
components:
  schemas:
    SocialProfile:
      type: object
      properties:
        id:
          type: integer
          example: 4
        username:
          type: string
          example: ic3peak
    Location:
      type: object
      properties:
        id:
          type: integer
          example: 4
        name:
          type: string
          example: X
        description:
          type: string
          example: X
        lat:
          type: number
          example: 55.7535579
        long:
          type: number
          example: 37.6187217
        score:
          type: number
          example: 4.6
  